apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-role
apiVersion: rbac.authorization.k8s.io/v1
rules:
- apiGroups: [""]
  resources:
  - nodes/metrics
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources:
  - resourcequotas
  verbs: ["get", "list","create", "delete"]
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-scraper-sa
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-role
subjects:
- kind: ServiceAccount
  name: metrics-scraper-sa
  namespace: default
