FROM python:latest

# Instalar el conector MySQL
RUN pip install mysql-connector-python

# Instalar kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && mv kubectl /usr/local/bin/kubectl \
    && chmod +x /usr/local/bin/kubectl

# Crear el directorio /scripts
RUN mkdir -p /scripts

# Copiar scripts de monitoreo
COPY pod-quota-to-zero.yaml /scripts/pod-quota-to-zero.yaml
COPY check_cpu_namespace.py /scripts/check_cpu_namespace.py

# Establecer el directorio de trabajo
WORKDIR /scripts

# Comando predeterminado
CMD ["python", "/scripts/check_cpu_namespace.py"]