apiVersion: batch/v1
kind: CronJob
metadata:
  name: check-cpu-namespace
spec:
  jobTemplate:
    metadata:
      name: check-cpu-namespace
    spec:
      template:
        spec:
          serviceAccount: metrics-scraper-sa
          containers:
          - image: samartinezcuello/check-cpu-namespace:latest
            name: check-cpu-namespace
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/4 * * * *'